name: "Check formatting of Rust code with rustfmt"

on:
  pull_request:
    branches:
      - '**'

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Use Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
    
    - name: Rustfmt Check + Annotations
      uses: Syndelis/rustfmt-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
