on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

      - name: Count approved reviews
        id: approved-reviews-counter
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APPROVED_REVIEWS_COUNT=$(gh api \
            /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            --jq 'map(select(.state == "APPROVED")) | length')

          echo "approved-reviews-count=$APPROVED_REVIEWS_COUNT" >> "$GITHUB_OUTPUT"

      - name: Echo approved reviews count
        run: echo "approved-reviews-count=[${{ steps.approved-reviews-counter.outputs.approved-reviews-count }}]"
