on:
  pull_request_review:
    types:
      - submitted

jobs:
  juggle_labels_on_approve:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

      - name: Count approved reviews
        id: approved-reviews-counter
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APPROVED_REVIEWS_COUNT=$(gh api \
            /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            --jq '[.[] | select(.state == "APPROVED") | .user.id] | unique | length')

          echo "approved-reviews-count=$APPROVED_REVIEWS_COUNT" >> "$GITHUB_OUTPUT"

      - name: Echo approved reviews count
        run: echo "approved-reviews-count=[${{ steps.approved-reviews-counter.outputs.approved-reviews-count }}]"

      - name: Remove 'waiting review' and add 'waiting QA' labels if the PR was approved
        if: steps.approved-reviews-counter.outputs.approved-reviews-count >= 1
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/waiting%20review \
            || true
          
          gh api \
            --method POST \
            /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
            -f labels[]='waiting QA'
