on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - converted_to_draft

jobs:
  add_waiting_review_label:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Label Conditionally
        uses: ./.github/actions/functional-labeler
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          when_pr_is: ready
          then_add_labels: waiting-1,waiting_2,esse label nao deve ser removido
          also_reverse: true
